name: Run Python Script

on:
  repository_dispatch:
    types: [my-cron-event] 
  workflow_dispatch:

permissions:
  contents: write


jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 2. Python環境のセットアップ（バージョンは必要に応じて変更してください）
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 依存ライブラリのインストール（requirements.txt がある場合のみ）
      - name: Install dependencies
        run: |
          pip install Pillow Scratchattach

      # 4. main.py の実行
      - name: Run main.py
        env:
          SCRATCH_PASSWORD: ${{ secrets.SCRATCH_PASSWORD }} 
          SCRATCH_USERNAME: ${{ secrets.SCRATCH_USERNAME }} 
        run: python main.py
