name: Run Python Script

on:
  workflow_dispatch: # 手動実行（緑のボタン）を有効化

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository code
        uses: actions/checkout@v4

        env:
          SCRATCH_PASSWORD: ${{ secrets.SCRATCH_PASSWORD }} 
          SCRATCH_USERNAME: ${{ secrets.SCRATCH_USERNAME }} 

      # 2. Python環境のセットアップ（バージョンは必要に応じて変更してください）
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 依存ライブラリのインストール（requirements.txt がある場合のみ）
      - name: Install dependencies
        run: |
          pip install Pillow Scratchattach

      # 4. main.py の実行
      - name: Run main.py
        run: python main.py
      - name: Upload PNG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-number-png           # ダウンロードするときのフォルダ名
          path: number_image.png        # Pythonコードで保存したPNGのファイル名

